## The Monty Hall Problem


Here's a fun and perhaps surprising statistical riddle, and a good way to get some practice writing python functions

In a gameshow, contestants try to guess which of 3 closed doors contain a cash prize (goats are behind the other two doors). Of course, the odds of choosing the correct door are 1 in 3. As a twist, the host of the show occasionally opens a door after a contestant makes his or her choice. This door is always one of the two the contestant did not pick, and is also always one of the goat doors (note that it is always possible to do this, since there are two goat doors). At this point, the contestant has the option of keeping his or her original choice, or swtiching to the other unopened door. The question is: is there any benefit to switching doors? The answer surprises many people who haven't heard the question before.

We can answer the problem by running simulations in Python. We'll do it in several parts.

First, write a function called `simulate_prizedoor`. This function will simulate the location of the prize in many games -- see the detailed specification below:

In [2]:
"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s, and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run

Returns
-------
sims : array
    Random array of 0s, 1s, and 2s

Example
-------
>>> print simulate_prizedoor(3)
array([0, 0, 2])
"""

import numpy as np
def simulate_prizedoor(nsim):
    #compute here
    answer = np.random.randint(0,3,nsim)
    return answer
#your code here

simulate_prizedoor(20)

array([2, 2, 0, 0, 2, 2, 0, 2, 0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 0, 2])

Next, write a function that simulates the contestant's guesses for `nsim` simulations. Call this function `simulate_guess`. The specs:

In [3]:
"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for

Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1, or 2

Example
-------
>>> print simulate_guess(5)
array([0, 0, 0, 0, 0])
"""

def simulate_guess(num):
    # will change this later to reflect randint(0,num_of_doors)
    return np.zeros(num)
    
#your code here
simulate_guess(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Next, write a function, `goat_door`, to simulate randomly revealing one of the goat doors that a contestant didn't pick.

In [10]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""
#your code here
def goat_door(np_array1, np_array2):
    a = []
    i = 0
    while i<len(np_array1):
        prize = np_array1[i]
        guess = np_array2[i]
        goat_door = {0,1,2} - set([guess,prize])
        a.append(goat_door.pop()) # just take the first element from the set.
        i+=1
    return np.array(a)

goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
        

array([2, 0, 0])

Write a function, `switch_guess`, that represents the strategy of always switching a guess after the goat door is opened.

In [11]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""
#your code here
def switch_guess(np_array1, np_array2):
    a = []
    i = 0
    while i<len(np_array1):
        guess = np_array1[i]
        goat_door = np_array2[i]
        switch_door = {0,1,2} - set([guess,goat_door])
        a.append(switch_door.pop()) # just take the first element from the set.
        i+=1
    return np.array(a)

switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))

array([2, 0, 0])

Last function: write a `win_percentage` function that takes an array of `guesses` and `prizedoors`, and returns the percent of correct guesses

In [26]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
-----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation

Returns
--------
percentage : number between 0 and 100
    The win percentage

Examples
---------
>>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
33.333
"""
#your code here
def win_percentage(np_array1, np_array2):
    return float(sum(np_array1 == np_array2))/len(np_array1) * 100

print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))

33.3333333333


Now, put it together. Simulate 10000 games where contestant keeps his original guess, and 10000 games where the contestant switches his door after a  goat door is revealed. Compute the percentage of time the contestant wins under either strategy. Is one strategy better than the other?

In [44]:
#your code here
def run_simulations():
    num_of_simulations = input("Enter the number of simulations you want to run:")
    prize_doors = simulate_prizedoor(num_of_simulations)
    guesses = simulate_guess(num_of_simulations)
    goat_doors = goat_door(prize_doors, guesses)
    switch_guesses = switch_guess(guesses, goat_doors)
    print "without switching (Jim) win percentage:", win_percentage(guesses, prize_doors)
    print "after switching win percentage:", win_percentage(switch_guesses, prize_doors)
    
run_simulations()
    


Enter the number of simulations you want to run:100000
without switching (Jim) win percentage: 33.384
after switching win percentage: 66.616


Many people find this answer counter-intuitive (famously, PhD mathematicians have incorrectly claimed the result must be wrong. Clearly, none of them knew Python). 

One of the best ways to build intuition about why opening a Goat door affects the odds is to re-run the experiment with 100 doors and one prize. If the game show host opens 98 goat doors after you make your initial selection, would you want to keep your first pick or switch? Can you generalize your simulation code to handle the case of `n` doors?